presentation-project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: root
      password: password
      port: 5432
      dbname: dbt
      schema: public
      threads: 1
      keepalives_idle: 0 # default 0, indicating the system default. See below
      connect_timeout: 10 # default 10 seconds
      retries: 1  # default 1 retry on error/timeout when opening connections