presentation:
  outputs:

    dev:
      type: postgres
      threads: 2
      host: 172.21.0.2
      port: 5432
      user: root
      pass: password
      dbname: modeling_layer
      schema: dev_schema

    prod:
      type: postgres
      threads: 2
      host: 172.21.0.2
      port: 5432
      user: root
      pass: password
      dbname: modelling_layer
      schema: prod_schema

  target: dev
