version: "1.0"
services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "dbt"
    ports:
      - "5432:5432"
    volumes:
      - ./pgsql-mnt/dvdrental:/var/lib/postgresql/data
      - ./pgsql-mnt/initData.sql:/docker-entrypoint-initdb.d/